version: "3"

services:
    postgres:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=password
    redis:
        image: redis
    api:
        image: multi-container-server:latest
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /usr/src/app/node_modules
            - ./server:/usr/src/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=password
            - PGPORT=5432
        depends_on: 
            - redis
            - postgres
    client:
        image: multi-container-client:latest
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /usr/src/app/node_modules
            - ./client:/usr/src/app
        depends_on: 
            - api
    worker:
        image: multi-container-worker:latest
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /usr/src/app/node_modules
            - ./worker:/usr/src/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on: 
            - redis
    nginx:
        image: multi-container-nginx:latest
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - "80:80"